apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews
    version: v1
spec:
  selector:
    matchLabels:
      app: reviews
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      serviceAccountName: ratings
      containers:
        - name: reviews
          image: istio/examples-bookinfo-reviews-v1:1.10.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-v1
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews
    version: v1
---
